name: tiktok_clone
description: A TikTok clone built with Flutter featuring video sharing, real-time chat, and social interactions.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # UI & Theming
  cupertino_icons: ^1.0.2
  google_fonts: ^6.1.0
  
  # State Management
  provider: ^6.1.1
  
  # Networking
  dio: ^5.4.0
  socket_io_client: ^2.0.3+1
  
  # Video Player
  video_player: ^2.8.1
  chewie: ^1.7.4
  
  # Image & Media
  image_picker: ^1.0.4
  cached_network_image: ^3.3.0
  
  # Storage & Persistence
  shared_preferences: ^2.2.2
  path_provider: ^2.1.1
  
  # Utilities
  uuid: ^4.2.1
  intl: ^0.19.0
  timeago: ^3.6.0
  
  # Animations
  lottie: ^2.7.0
  flutter_staggered_animations: ^1.1.1
  
  # Permissions
  permission_handler: ^11.1.0
  
  # Camera
  camera: ^0.10.5+5
  
  # File handling
  path: ^1.8.3
  
  # HTTP multipart
  http: ^1.1.2
  
  # Icons
  flutter_svg: ^2.0.9
  
  # Pull to refresh
  pull_to_refresh: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/animations/
    
  fonts:
    - family: ProximaNova
      fonts:
        - asset: assets/fonts/ProximaNova-Regular.ttf
        - asset: assets/fonts/ProximaNova-Bold.ttf
          weight: 700
        - asset: assets/fonts/ProximaNova-Semibold.ttf
          weight: 600